# Generated by Django 2.1.3 on 2019-10-21 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=100)),
                ('wingspan', models.CharField(max_length=100)),
                ('mass', models.IntegerField(default=0)),
                ('lifespan', models.IntegerField(default=0)),
                ('conservation_status', models.CharField(choices=[('Extinct', 'EX'), ('Etinct in the wild', 'EW'), ('Crtically Endangered', 'CR'), ('Endangered', 'EN'), ('Vulnerable', 'VU'), ('Near threatened', 'NT'), ('Least concern', 'LC'), ('Not evaluated', 'NE')], default='Not evaluated', max_length=100)),
                ('speed', models.IntegerField(default=0)),
                ('fact', models.CharField(max_length=100)),
            ],
        ),
    ]
