# Generated by Django 2.1.3 on 2019-11-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bird_identifier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_photo', models.ImageField(upload_to='results/')),
            ],
        ),
    ]
