# Generated by Django 2.1.3 on 2019-11-07 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bird_identifier', '0002_userphoto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPhoto',
            new_name='ModelWithFileField',
        ),
    ]
